name: Deploy DRT

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: [self-hosted]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install App Dependencies
      run: |
        npm install
    - name: Build Next Application
      run: |
        npm run build
    # - name: Start PM2
    #   run: |
    #     pm2 delete --silent drt.front || :; pm2 start pm2.config.json